/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import Configuraciones.Configuraciones;
import DBObjetos.Usuario;
import Graficas.AvisosFrame;
import Graficas.ObservarGraficas;
import INVENTARIO.Principal2_0;
import PanelUsuarios.UsuariosPanel;
import Venta.Venta;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import login.LOGINN;
import login.SesionManager;

/**
 *
 * @author braul
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
       private static MenuPrincipal instance;
     private Usuario usuarioLogueado;

    
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null); // Centramos la ventana en la pantalla

    }
       
    public void initialize(Usuario usuario) {
        this.usuarioLogueado = usuario;
                System.out.println("El rol del usuario es: " + usuario.getNombreUsuario());

        configurarVisibilidadComponentes();
    }  
      

    
        private void configurarVisibilidadComponentes() {
        // Asegúrate de que los componentes están inicializados antes de llamar este método
        if (usuarioLogueado.getRol() == Usuario.Rol.EMPLEADO) {
            PConfiguraciones.setVisible(false);
            PUsuarios.setVisible(false);
             PGraficas.setVisible(false);
            // Hacer invisibles otros labels que no deben verse por el empleado
        } else if (usuarioLogueado.getRol() == Usuario.Rol.ADMINISTRADOR) {
            // El administrador puede ver todo, así que no necesitas hacer nada aquí
        }
    }
        
    
    public static MenuPrincipal getInstance() {
        if (instance == null) {
            instance = new MenuPrincipal();
        }
        return instance;
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logout = new javax.swing.JLabel();
        PConfiguraciones = new javax.swing.JPanel();
        lblConfiguraciones = new javax.swing.JLabel();
        PInventario = new javax.swing.JPanel();
        lblInventario = new javax.swing.JLabel();
        PGraficas = new javax.swing.JPanel();
        lblGraficas = new javax.swing.JLabel();
        PUsuarios = new javax.swing.JPanel();
        lblUsuarios = new javax.swing.JLabel();
        PVenta = new javax.swing.JPanel();
        lblVenta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/CerrarSesion32px.png"))); // NOI18N
        Logout.setText("Cerrar Sesión");
        Logout.setToolTipText("");
        Logout.setAlignmentX(0.5F);
        Logout.setFocusable(false);
        Logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 90, 70));

        PConfiguraciones.setBackground(new java.awt.Color(191, 241, 247));

        lblConfiguraciones.setBackground(new java.awt.Color(204, 255, 153));
        lblConfiguraciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblConfiguraciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfiguraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Configuraciones128px.png"))); // NOI18N
        lblConfiguraciones.setText("configuraciones");
        lblConfiguraciones.setToolTipText("");
        lblConfiguraciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblConfiguraciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblConfiguraciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfiguracionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConfiguracionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConfiguracionesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PConfiguracionesLayout = new javax.swing.GroupLayout(PConfiguraciones);
        PConfiguraciones.setLayout(PConfiguracionesLayout);
        PConfiguracionesLayout.setHorizontalGroup(
            PConfiguracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
            .addGroup(PConfiguracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblConfiguraciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
        );
        PConfiguracionesLayout.setVerticalGroup(
            PConfiguracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
            .addGroup(PConfiguracionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblConfiguraciones, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        );

        getContentPane().add(PConfiguraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        PInventario.setBackground(new java.awt.Color(191, 241, 247));

        lblInventario.setBackground(new java.awt.Color(204, 255, 153));
        lblInventario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Inventario128px.png"))); // NOI18N
        lblInventario.setText("Inventario");
        lblInventario.setToolTipText("");
        lblInventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblInventario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInventarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInventarioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PInventarioLayout = new javax.swing.GroupLayout(PInventario);
        PInventario.setLayout(PInventarioLayout);
        PInventarioLayout.setHorizontalGroup(
            PInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
            .addGroup(PInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblInventario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
        );
        PInventarioLayout.setVerticalGroup(
            PInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
            .addGroup(PInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblInventario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        );

        getContentPane().add(PInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        PGraficas.setBackground(new java.awt.Color(191, 241, 247));

        lblGraficas.setBackground(new java.awt.Color(204, 255, 153));
        lblGraficas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGraficas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGraficas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Graficas128px.png"))); // NOI18N
        lblGraficas.setText("Graficas");
        lblGraficas.setToolTipText("");
        lblGraficas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblGraficas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblGraficas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGraficasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGraficasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGraficasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PGraficasLayout = new javax.swing.GroupLayout(PGraficas);
        PGraficas.setLayout(PGraficasLayout);
        PGraficasLayout.setHorizontalGroup(
            PGraficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
            .addGroup(PGraficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblGraficas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
        );
        PGraficasLayout.setVerticalGroup(
            PGraficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
            .addGroup(PGraficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblGraficas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        );

        getContentPane().add(PGraficas, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        PUsuarios.setBackground(new java.awt.Color(191, 241, 247));

        lblUsuarios.setBackground(new java.awt.Color(204, 255, 153));
        lblUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Usuarios128px.png"))); // NOI18N
        lblUsuarios.setText("Usuarios");
        lblUsuarios.setToolTipText("");
        lblUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsuariosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PUsuariosLayout = new javax.swing.GroupLayout(PUsuarios);
        PUsuarios.setLayout(PUsuariosLayout);
        PUsuariosLayout.setHorizontalGroup(
            PUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
            .addGroup(PUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
        );
        PUsuariosLayout.setVerticalGroup(
            PUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
            .addGroup(PUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        );

        getContentPane().add(PUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        PVenta.setBackground(new java.awt.Color(191, 241, 247));

        lblVenta.setBackground(new java.awt.Color(204, 255, 153));
        lblVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Venta128px.png"))); // NOI18N
        lblVenta.setText("Venta");
        lblVenta.setToolTipText("");
        lblVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVentaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PVentaLayout = new javax.swing.GroupLayout(PVenta);
        PVenta.setLayout(PVentaLayout);
        PVentaLayout.setHorizontalGroup(
            PVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
            .addGroup(PVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
        );
        PVentaLayout.setVerticalGroup(
            PVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
            .addGroup(PVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        );

        getContentPane().add(PVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 870, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblInventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventarioMouseEntered
   ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/Inventario128px.png"));
    Image img = icon.getImage();
    Image scaledImg = img.getScaledInstance(150, 150, Image.SCALE_SMOOTH);
    lblInventario.setIcon(new ImageIcon(scaledImg));
    }//GEN-LAST:event_lblInventarioMouseEntered

    private void lblInventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventarioMouseExited
    ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/Inventario128px.png"));
    lblInventario.setIcon(icon);
    // No es necesario cambiar el color si ya es el correcto

    }//GEN-LAST:event_lblInventarioMouseExited

    private void lblInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventarioMouseClicked
        Principal2_0 principalWindow = Principal2_0.getInstance();
         principalWindow.initialize(SesionManager.getInstance().getUsuarioLogueado());
        principalWindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblInventarioMouseClicked

    private void lblVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentaMouseClicked
    Venta ventaWindow = Venta.getInstance();
    ventaWindow.initialize(SesionManager.getInstance().getUsuarioLogueado());
    ventaWindow.setVisible(true);
    this.setVisible(false);
       

    }//GEN-LAST:event_lblVentaMouseClicked

    private void lblVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentaMouseEntered
   ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/Venta128px.png"));
    Image img = icon.getImage();
    Image scaledImg = img.getScaledInstance(150, 150, Image.SCALE_SMOOTH);
    lblVenta.setIcon(new ImageIcon(scaledImg));
    }//GEN-LAST:event_lblVentaMouseEntered

    private void lblVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentaMouseExited
    ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/Venta128px.png"));
    lblVenta.setIcon(icon);
    // No es necesario cambiar el color si ya es el correcto

    }//GEN-LAST:event_lblVentaMouseExited

    private void lblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseClicked
    UsuariosPanel ventaWindow = UsuariosPanel.getInstance();
    ventaWindow.initialize(SesionManager.getInstance().getUsuarioLogueado());
    ventaWindow.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_lblUsuariosMouseClicked

    private void lblUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseEntered
   ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/Usuarios128px.png"));
    Image img = icon.getImage();
    Image scaledImg = img.getScaledInstance(150, 150, Image.SCALE_SMOOTH);
    lblUsuarios.setIcon(new ImageIcon(scaledImg));
    }//GEN-LAST:event_lblUsuariosMouseEntered

    private void lblUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuariosMouseExited
    ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/Usuarios128px.png"));
    lblUsuarios.setIcon(icon);
    }//GEN-LAST:event_lblUsuariosMouseExited

    private void lblConfiguracionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfiguracionesMouseClicked
    Configuraciones configWindow = Configuraciones.getInstance();
    configWindow.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_lblConfiguracionesMouseClicked

    private void lblConfiguracionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfiguracionesMouseEntered
   ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/Configuraciones128px.png"));
    Image img = icon.getImage();
    Image scaledImg = img.getScaledInstance(150, 150, Image.SCALE_SMOOTH);
    lblConfiguraciones.setIcon(new ImageIcon(scaledImg));
    }//GEN-LAST:event_lblConfiguracionesMouseEntered

    private void lblConfiguracionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfiguracionesMouseExited
    ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/Configuraciones128px.png"));
    lblConfiguraciones.setIcon(icon);
    }//GEN-LAST:event_lblConfiguracionesMouseExited

    private void lblGraficasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGraficasMouseClicked
        AvisosFrame avisosFrame = AvisosFrame.getInstance();
        avisosFrame.initialize(SesionManager.getInstance().getUsuarioLogueado());
        avisosFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblGraficasMouseClicked

    private void lblGraficasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGraficasMouseEntered
   ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/Graficas128px.png"));
    Image img = icon.getImage();
    Image scaledImg = img.getScaledInstance(150, 150, Image.SCALE_SMOOTH);
    lblGraficas.setIcon(new ImageIcon(scaledImg));
    }//GEN-LAST:event_lblGraficasMouseEntered

    private void lblGraficasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGraficasMouseExited
    ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/Graficas128px.png"));
    lblGraficas.setIcon(icon);
    }//GEN-LAST:event_lblGraficasMouseExited

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        logout();
    }//GEN-LAST:event_LogoutMouseClicked

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        Logout.setOpaque(true); // Permite que el JLabel tenga color de fondo
        Logout.setBackground(new Color(255, 0, 0, 192)); // Color rojo opaco
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited
        Logout.setOpaque(false); // Elimina el color de fondo
        Logout.setBackground(null); // Restaura el color de fondo original
    }//GEN-LAST:event_LogoutMouseExited
    // Método para cerrar sesión
    private void logout() {
        SesionManager.getInstance().logout();
        LOGINN loginWindow = new LOGINN();
        loginWindow.setVisible(true);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logout;
    private javax.swing.JPanel PConfiguraciones;
    private javax.swing.JPanel PGraficas;
    private javax.swing.JPanel PInventario;
    private javax.swing.JPanel PUsuarios;
    private javax.swing.JPanel PVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblConfiguraciones;
    private javax.swing.JLabel lblGraficas;
    private javax.swing.JLabel lblInventario;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JLabel lblVenta;
    // End of variables declaration//GEN-END:variables
}