/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;
import Consultas.CONSULTASDAO;
import ConexionDB.Conexion_DB;
import DBObjetos.*;

import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author braul
 */
public class FormPrimera extends JFrame {

    /**
     * Creates new form FormularioNuevoUsuario
     */
    
    private String rolSeleccionado;
    boolean visible = false;

    public FormPrimera(String rol) {
       this.rolSeleccionado = rol; // Establece el rol para el formulario
        initComponents();
        lblRoles.setText(rolSeleccionado); // Muestra el rol en la etiqueta
        
    
    
    

    }

    
private void volverALogin() {
    this.dispose();  // Cierra FormPrimera antes de mostrar LOGINN
    java.awt.EventQueue.invokeLater(() -> {
        new LOGINN().setVisible(true);
    });
}


    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        lblRoles = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        nomUsuario = new javax.swing.JTextField();
        ContraseñaToken = new javax.swing.JPasswordField();
        Contraseña = new javax.swing.JPasswordField();
        btnContraseña = new javax.swing.JButton();
        btnContraseña1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 90, 40));

        lblRoles.setText("REGISTRARSE");
        getContentPane().add(lblRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 0, 117, -1));

        Nombre.setText("Nombre");
        Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        Nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NombreFocusLost(evt);
            }
        });
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 179, 70));

        Apellido.setText("Apellido");
        Apellido.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido"));
        Apellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ApellidoFocusLost(evt);
            }
        });
        getContentPane().add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 207, 70));

        Correo.setText("Correo");
        Correo.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo"));
        Correo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CorreoFocusLost(evt);
            }
        });
        getContentPane().add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 260, 70));

        nomUsuario.setText("Nombre de usuario");
        nomUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre de Usuario"));
        nomUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomUsuarioFocusLost(evt);
            }
        });
        getContentPane().add(nomUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 311, 80));

        ContraseñaToken.setText("Contraseña token");
        ContraseñaToken.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));
        ContraseñaToken.setEchoChar('\u0000');
        ContraseñaToken.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ContraseñaTokenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ContraseñaTokenFocusLost(evt);
            }
        });
        ContraseñaToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaTokenActionPerformed(evt);
            }
        });
        getContentPane().add(ContraseñaToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 152, 70));
        ContraseñaToken.getAccessibleContext().setAccessibleName("Contraseña Token");

        Contraseña.setText("Contraseña");
        Contraseña.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));
        Contraseña.setEchoChar('\u0000');
        Contraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ContraseñaFocusLost(evt);
            }
        });
        getContentPane().add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 152, 70));

        btnContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(btnContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 40, 40));

        btnContraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContraseña1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 40, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
    private boolean validarCampos() {
        String usuario = nomUsuario.getText().trim();
        String contraseñaPlana = new String(Contraseña.getPassword()).trim();
        String correo = Correo.getText().trim();
        String nombre = Nombre.getText().trim();
        String apellido = Apellido.getText().trim();
        String contraseñaTokenPlana = new String(ContraseñaToken.getPassword()).trim();

        // Verifica que se hayan ingresado todos los campos
        boolean camposValidos = !usuario.isEmpty() && !contraseñaPlana.isEmpty() &&
                                !correo.isEmpty() && !nombre.isEmpty() && !apellido.isEmpty();

        // Validación del formato del correo electrónico
        boolean esCorreoValido = correo.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$");

        // Validación del nombre y apellido (solo letras)
        boolean esNombreValido = nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+");
        boolean esApellidoValido = apellido.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+");

        // Validación de la longitud de la contraseña
        boolean esContraseñaValida = contraseñaPlana.length() >= 8;

        if (!camposValidos) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos requeridos.");
            return false;
        }

        if (!esCorreoValido) {
            JOptionPane.showMessageDialog(this, "El formato del correo electrónico no es válido.");
            return false;
        }

        if (!esNombreValido) {
            JOptionPane.showMessageDialog(this, "El nombre solo puede contener letras.");
            return false;
        }

        if (!esApellidoValido) {
            JOptionPane.showMessageDialog(this, "El apellido solo puede contener letras.");
            return false;
        }

        if (!esContraseñaValida) {
            JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 8 caracteres.");
            return false;
        }

        return true;
    }
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (!validarCampos()) {
            return; // Si la validación falla, no continuar
        }

        // Obtener valores de los campos de texto
        String usuario = nomUsuario.getText().trim();
        String contraseñaPlana = new String(Contraseña.getPassword()).trim();
        String correo = Correo.getText().trim();
        String nombre = Nombre.getText().trim();
        String apellido = Apellido.getText().trim();
        String contraseñaTokenPlana = new String(ContraseñaToken.getPassword()).trim();

        try {
            // Hashear la contraseña y el token antes de enviarlos a la base de datos
            String contraseñaHasheada = HashingUtil.hashPassword(contraseñaPlana);
            String contraseñaTokenHasheada = HashingUtil.hashPassword(contraseñaTokenPlana);
            if (contraseñaHasheada == null || contraseñaTokenHasheada == null) {
                throw new IllegalArgumentException("No se pudo hashear la contraseña o el token.");
            }

            // Crea una instancia de CONSULTASDAO
            CONSULTASDAO dao = new CONSULTASDAO(Conexion_DB.getConexion());

            // El método crearEmpleado ahora también incluye contraseñaToken
            boolean exito = dao.crearEmpleado(usuario, contraseñaHasheada, Usuario.Rol.ADMINISTRADOR, contraseñaTokenHasheada, correo, nombre, apellido);

            if (exito) {
                JOptionPane.showMessageDialog(this, "Empleado agregado correctamente.");
                resetFormulario();
            } else {
                JOptionPane.showMessageDialog(this, "El nombre de usuario ya existe, por favor cree uno nuevo.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos: " + ex.getMessage());
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        volverALogin();

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void NombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreFocusGained
        if(Nombre.getText().equals("Nombre")){
            Nombre.setText(null);
            Nombre.requestFocus();
            Estilos.removePlaceholderStyle(Nombre);
        }
    }//GEN-LAST:event_NombreFocusGained

    private void NombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreFocusLost
        if (Nombre.getText().length() == 0) {
            Estilos.addPlaceholderStyle(Nombre);
            Nombre.setText("Nombre");
        } else {
            if (!Nombre.getText().matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+")) {
                JOptionPane.showMessageDialog(this, "El nombre solo puede contener letras.");
                Nombre.requestFocus();
            }
        }
    }//GEN-LAST:event_NombreFocusLost

    private void ApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ApellidoFocusGained
        if(Apellido.getText().equals("Apellido")){
            Apellido.setText(null);
            Apellido.requestFocus();
            Estilos.removePlaceholderStyle(Apellido);
        }
    }//GEN-LAST:event_ApellidoFocusGained

    private void ApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ApellidoFocusLost
        if (Apellido.getText().length() == 0) {
            Estilos.addPlaceholderStyle(Apellido);
            Apellido.setText("Apellido");
        } else {
            if (!Apellido.getText().matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+")) {
                JOptionPane.showMessageDialog(this, "El apellido solo puede contener letras.");
                Apellido.requestFocus();
            }
        }
    }//GEN-LAST:event_ApellidoFocusLost

    private void CorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CorreoFocusGained
        if(Correo.getText().equals("Correo")){
            Correo.setText(null);
            Correo.requestFocus();
            Estilos.removePlaceholderStyle(Correo);
        }
    }//GEN-LAST:event_CorreoFocusGained

    private void CorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CorreoFocusLost
        if (Correo.getText().length() == 0) {
            Estilos.addPlaceholderStyle(Correo);
            Correo.setText("Correo");
        } else {
            if (!Correo.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$")) {
                JOptionPane.showMessageDialog(this, "El formato del correo electrónico no es válido.");
                Correo.requestFocus();
            }
        }
    }//GEN-LAST:event_CorreoFocusLost

    private void nomUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomUsuarioFocusGained
        if(nomUsuario.getText().equals("Nombre de usuario")){
            nomUsuario.setText(null);
            nomUsuario.requestFocus();
            Estilos.removePlaceholderStyle(nomUsuario);
        }
    }//GEN-LAST:event_nomUsuarioFocusGained

    private void nomUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomUsuarioFocusLost
        if(nomUsuario.getText().length()==0){
            Estilos.addPlaceholderStyle(nomUsuario);
            nomUsuario.setText("Nombre de usuario");
        }
    }//GEN-LAST:event_nomUsuarioFocusLost

    private void ContraseñaTokenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContraseñaTokenFocusGained
        if (new String(ContraseñaToken.getPassword()).equals("Contraseña")) {
            ContraseñaToken.setText(null);
            ContraseñaToken.requestFocus();
            ContraseñaToken.setEchoChar('*');
            Estilos.removePlaceholderStyle(ContraseñaToken);
        }
    }//GEN-LAST:event_ContraseñaTokenFocusGained

    private void ContraseñaTokenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContraseñaTokenFocusLost
        String contraseña = new String(ContraseñaToken.getPassword());
        if (contraseña.length() == 0) {
            Estilos.addPlaceholderStyle(ContraseñaToken);
            ContraseñaToken.setText("Contraseña");
            ContraseñaToken.setEchoChar('\u0000');
        } else if (contraseña.length() < 8) {
            JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 8 caracteres.");
            ContraseñaToken.requestFocus();
        }
    }//GEN-LAST:event_ContraseñaTokenFocusLost

    private void ContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContraseñaFocusGained
        if (new String(Contraseña.getPassword()).equals("Contraseña")) {
            Contraseña.setText(null);
            Contraseña.requestFocus();
            Contraseña.setEchoChar('*');
            Estilos.removePlaceholderStyle(Contraseña);
        }
    }//GEN-LAST:event_ContraseñaFocusGained

    private void ContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContraseñaFocusLost
        String contraseña = new String(Contraseña.getPassword());
        if (contraseña.length() == 0) {
            Estilos.addPlaceholderStyle(Contraseña);
            Contraseña.setText("Contraseña");
            Contraseña.setEchoChar('\u0000');
        } else if (contraseña.length() < 8) {
            JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 8 caracteres.");
            Contraseña.requestFocus();
        }
    }//GEN-LAST:event_ContraseñaFocusLost

    private void btnContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContraseñaActionPerformed
        // TODO add your handling code here:
        if (visible) {
            Contraseña.setEchoChar('*'); // Oculta la contraseña
            visible = false;
            btnContraseña.setIcon(new ImageIcon(getClass().getResource("/Icons/cerrarOjo.png")));

        } else {
            Contraseña.setEchoChar((char) 0); // Muestra la contraseña
            visible = true;
            // Cambia el icono a abrirOjo
            btnContraseña.setIcon(new ImageIcon(getClass().getResource("/Icons/abrirOjo.png")));

        }
    }//GEN-LAST:event_btnContraseñaActionPerformed

    private void btnContraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContraseña1ActionPerformed
        // TODO add your handling code here:
        if (visible) {
            ContraseñaToken.setEchoChar('*'); // Oculta la contraseña
            visible = false;
            btnContraseña.setIcon(new ImageIcon(getClass().getResource("/Icons/cerrarOjo.png")));

        } else {
            ContraseñaToken.setEchoChar((char) 0); // Muestra la contraseña
            visible = true;
            // Cambia el icono a abrirOjo
            btnContraseña.setIcon(new ImageIcon(getClass().getResource("/Icons/abrirOjo.png")));

        }
    }//GEN-LAST:event_btnContraseña1ActionPerformed

    private void ContraseñaTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaTokenActionPerformed

private void resetFormulario() {
    // Restablecer los campos del formulario
    nomUsuario.setText("");
    ContraseñaToken.setText("");
    Correo.setText("");
    Nombre.setText("");
    Apellido.setText("");
    //lblmensaje.setText("");         // Limpiar mensajes de respuesta
    // Restablecer los colores de las etiquetas a negro
//    lblUsuario.setForeground(Color.BLACK);
//    lblContraseña.setForeground(Color.BLACK);
//    lblCorreo.setForeground(Color.BLACK);
//    lblNombre.setForeground(Color.BLACK);
//    lblApellido.setForeground(Color.BLACK);
}



  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JPasswordField ContraseñaToken;
    private javax.swing.JTextField Correo;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnContraseña;
    private javax.swing.JButton btnContraseña1;
    private javax.swing.JLabel lblRoles;
    private javax.swing.JTextField nomUsuario;
    // End of variables declaration//GEN-END:variables
}
